# Generated by Django 4.0.2 on 2022-02-14 09:03

import api.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(validators=[django.core.validators.MinValueValidator(0.001)])),
                ('width', models.FloatField(validators=[django.core.validators.MinValueValidator(0.001)])),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0.001)])),
                ('area', models.FloatField(validators=[api.models.area_validator, api.models.boxes_in_a_week_validator])),
                ('volume', models.FloatField(validators=[api.models.volume_validator])),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, validators=[api.models.boxes_in_a_week_by_user_validator])),
            ],
        ),
    ]
